#Deploy to AWS Ec2
stages:
  - deploy

# Deploy job
deploy:
 
  # Attach Deploy job to Deploy stage
  stage: deploy
  # Config to use our Runner with Executor Shell
  tags:
    - appearz-runner 
  script:
    # Only copy changed files to project folder
    
    - echo "$USER"
    - echo "Deployment Process Started"
    - cd /home/gitlab-runner/builds/
    - rm -rf appearz-web/
    - git clone https://gitlab+deploy-token-536842:qVyGB1QNYxyTcLh6rKtQ@gitlab.com/outshade/appearz/appearz-web.git
    - cd appearz-web/
    - npm install
    # Start NodeJS service
    - nohup npm start -S 0.0.0.0:3000 > /dev/null 2>&1 &
    - echo "Deployment Completion Successful"
    - exit
  only:
    - main