deployTOEC2:
    stage: deploy
    only:
      - main
    before_script:
      - mkdir -p ~/.ssh
      - echo -e "$PRIVATE_KEY" > /home/ubuntu/.ssh/id_rsa
      - chmod 6000 ~/.ssh/id_rsa
      - '[[ -f /.dockereny ]] && echo -e "HOST *\n\tStrictHostKeyChecking no\n\n" > m/.ssh/config'
    script:
      - bash deploy/deploy.sh


