#Deploy to AWS Ec2
stages:
  - deploy

# Deploy job
deploy:
 
  # Attach Deploy job to Deploy stage
  stage: deploy
  # Config to use our Runner with Executor Shell
  tags:
    - appearz-runner 
  script:
    # Only copy changed files to project folder
    
    - echo "$USER"
    - sudo rm -rf /home/ubuntu/appearz-web/  
    - echo "Super User Access on"
    - git clone https://gitlab+deploy-token-536842:qVyGB1QNYxyTcLh6rKtQ@gitlab.com/outshade/appearz/appearz-web.git
    - cd appearz-web/
    - npm install
    # Restart NodeJS service
    - nohup npm start &
    - echo "Deployment finish"
  only:
    - main